-- GameSurf NPC Kit — Supabase Schema Setup
-- Run this migration against your Supabase database to create the
-- required tables for the NPC dialogue and memory system.
--
-- Usage:
--   Via Supabase Dashboard: SQL Editor > paste and run
--   Via CLI: supabase db push (if using local Supabase)

-- ── Player Profiles ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.player_profiles (
    player_id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── NPC Profiles ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.npc_profiles (
    npc_id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    artifact_key TEXT,
    subject TEXT,
    subject_focus TEXT,
    npc_scope TEXT DEFAULT 'instructor',
    personality JSONB DEFAULT '{}',
    voice_rules JSONB DEFAULT '[]',
    domain_knowledge JSONB DEFAULT '[]',
    generation_defaults JSONB DEFAULT '{}',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ── Dialogue Sessions ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.dialogue_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id TEXT NOT NULL,
    npc_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at TIMESTAMPTZ,
    turn_count INTEGER NOT NULL DEFAULT 0,
    raw_json JSONB NOT NULL DEFAULT '{}'
);

-- ── Dialogue Turns ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.dialogue_turns (
    turn_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES public.dialogue_sessions(session_id),
    player_message TEXT NOT NULL,
    npc_response TEXT NOT NULL,
    raw_json JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── NPC Memories ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.npc_memories (
    memory_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id TEXT NOT NULL,
    npc_id TEXT NOT NULL,
    summary TEXT NOT NULL,
    raw_json JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_dialogue_sessions_player_npc
    ON public.dialogue_sessions(player_id, npc_id);
CREATE INDEX IF NOT EXISTS idx_dialogue_turns_session
    ON public.dialogue_turns(session_id);
CREATE INDEX IF NOT EXISTS idx_npc_memories_player_npc
    ON public.npc_memories(player_id, npc_id);

-- ── RLS Policies ─────────────────────────────────────────────────────────────
ALTER TABLE public.player_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.npc_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dialogue_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dialogue_turns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.npc_memories ENABLE ROW LEVEL SECURITY;

-- Service role bypass (for server-side access)
CREATE POLICY "Service role full access" ON public.player_profiles
    FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role full access" ON public.npc_profiles
    FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role full access" ON public.dialogue_sessions
    FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role full access" ON public.dialogue_turns
    FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role full access" ON public.npc_memories
    FOR ALL USING (auth.role() = 'service_role');

-- Anon read access for NPC profiles (public data)
CREATE POLICY "Anon read npc_profiles" ON public.npc_profiles
    FOR SELECT USING (true);
