create table if not exists public.test_results (
    test_result_id bigint generated by default as identity primary key,
    run_id text,
    player_id text,
    player_name text,
    npc_id text,
    session_id uuid,
    phase text,
    turn_count integer not null default 0,
    memory_created boolean,
    memory_loaded_on_start boolean,
    memory_persistence_verified boolean,
    memory_used_in_response boolean,
    memory_response_reason text,
    memory_retry_attempts integer,
    memory_retry_reason text,
    memory_quality_reason text,
    history_verified boolean,
    player_memories_verified boolean,
    god_memory_verified boolean,
    identity_verified boolean,
    message_preview text,
    response_preview text,
    error text,
    duration_seconds double precision,
    raw_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.test_results
    add column if not exists run_id text,
    add column if not exists player_name text,
    add column if not exists session_id uuid,
    add column if not exists turn_count integer not null default 0,
    add column if not exists memory_used_in_response boolean,
    add column if not exists memory_response_reason text,
    add column if not exists memory_retry_attempts integer,
    add column if not exists memory_retry_reason text,
    add column if not exists history_verified boolean,
    add column if not exists player_memories_verified boolean,
    add column if not exists god_memory_verified boolean,
    add column if not exists message_preview text,
    add column if not exists response_preview text,
    add column if not exists raw_json jsonb not null default '{}'::jsonb,
    add column if not exists created_at timestamptz not null default now();

create index if not exists test_results_run_created_idx
    on public.test_results (run_id, created_at desc);

create index if not exists test_results_player_npc_created_idx
    on public.test_results (player_id, npc_id, created_at desc);

create or replace function public.summarize_dialogue_session(
    session_id_param uuid,
    player_id_param text,
    npc_id_param text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    turn_count integer;
    summary_text text;
    lower_summary text;
    memory_kind text;
begin
    select count(*)
    into turn_count
    from public.dialogue_turns
    where session_id = session_id_param;

    if turn_count = 0 then
        summary_text := 'No dialogue turns were recorded for this session.';
        memory_kind := 'empty_session';
    else
        select string_agg(
            'Player: ' || left(player_message, 240) || E'\nNPC: ' ||
            left(
                regexp_replace(
                    regexp_replace(
                        npc_response,
                        E'^(system|npc):\\s*You are[^\\n]*\\n', '', 'i'
                    ),
                    E'^(system|npc):\\s*You are[^\\n]*', '', 'i'
                ),
                240
            ),
            E'\n'
            order by created_at
        )
        into summary_text
        from public.dialogue_turns
        where session_id = session_id_param;

        lower_summary := lower(coalesce(summary_text, ''));
        if lower_summary like '%do you remember%'
           or lower_summary like '%last conversation%'
           or lower_summary like '%past session%'
           or lower_summary like '%our previous conversation%' then
            memory_kind := 'recall_probe';
        else
            memory_kind := 'session_summary';
        end if;
    end if;

    insert into public.npc_memories (
        player_id,
        npc_id,
        summary,
        raw_json
    )
    values (
        player_id_param,
        npc_id_param,
        left(summary_text, 2000),
        jsonb_build_object(
            'session_id', session_id_param,
            'session_turn_count', turn_count,
            'summarizer', 'postgres_compact_v2',
            'memory_kind', memory_kind
        )
    );
end;
$$;
