create extension if not exists pgcrypto;

create table if not exists public.dialogue_sessions (
    session_id uuid primary key default gen_random_uuid(),
    player_id text not null,
    npc_id text not null,
    status text not null default 'active',
    started_at timestamptz not null default now(),
    ended_at timestamptz,
    raw_json jsonb not null default '{}'::jsonb
);

create index if not exists dialogue_sessions_player_npc_started_idx
    on public.dialogue_sessions (player_id, npc_id, started_at desc);

create table if not exists public.dialogue_turns (
    turn_id bigint generated by default as identity primary key,
    session_id uuid not null references public.dialogue_sessions (session_id) on delete cascade,
    player_message text not null,
    npc_response text not null,
    raw_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists dialogue_turns_session_created_idx
    on public.dialogue_turns (session_id, created_at);

create table if not exists public.npc_memories (
    memory_id bigint generated by default as identity primary key,
    player_id text not null,
    npc_id text not null,
    summary text not null,
    created_at timestamptz not null default now(),
    raw_json jsonb not null default '{}'::jsonb
);

create index if not exists npc_memories_player_npc_created_idx
    on public.npc_memories (player_id, npc_id, created_at desc);
